{{- if or .Values.rbac.create .Values.rbac.installOnlyRbac }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "inventa-operator.serviceAccountName" . }}
  labels:
    {{- include "inventa-operator.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}