{{- if not .Values.rbac.installOnlyRbac }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "crossplane-operator-dfds.fullname" . }}
  labels:
    {{- include "crossplane-operator-dfds.labels" . | nindent 4 }}
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      {{- include "crossplane-operator-dfds.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "crossplane-operator-dfds.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "crossplane-operator-dfds.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: DFDS_CROSSPLANE_ENABLED_ANNOTATION_NAME
              value: {{ .Values.crossplaneOperatorDfds.enableAnnotionName }}
            - name: DFDS_CROSSPLANE_AWS_ACCOUNT_ID_ANNOTATION_NAME
              value: {{ .Values.crossplaneOperatorDfds.awsAccountAnnotationName }}
              
          # ports:
          #   - name: http
          #     containerPort: 80
          #     protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end -}}