{{- if or .Values.rbac.create .Values.rbac.installOnlyRbac }}
{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "crossplane-operator-dfds.serviceAccountName" . }}
  labels:
    {{- include "crossplane-operator-dfds.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}
