# This is a basic workflow to help you get started with Actions

name: Helm Release

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Download Helm CLI
        run: |
          curl -L https://get.helm.sh/helm-v{{ helm_version }}-linux-amd64.tar.gz -o helm.tar.gz
          tar zxvf helm.tar.gz
          chmod +x linux-amd64/helm

      - name: Create Helm Releases
        run : |
          for f in charts/*; do
            linux-amd64/helm package $f
          done

      - name: Switch branch and publish
        run: |
          git checkout -f gh-pages
          linux-amd64/helm repo index .
          if [[ -d "linux-amd" ]]; then
            rm -rf "linux-amd"
          fi
          git add index.yaml *.tgz
          git commit -m "Upgraded the Helm index"
