# This is a basic workflow to help you get started with Actions

name: Helm Release

on:
  # push:
  #   branches: [ "main", "master" ]
  # pull_request:
  #   branches: [ "main", "master" ]

  workflow_dispatch:

env:
  HELM_VERSION: "v3.8.1"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Download Helm CLI
        run: |
          curl -L https://get.helm.sh/helm-$HELM_VERSION-linux-amd64.tar.gz -o helm.tar.gz
          tar zxvf helm.tar.gz
          chmod +x linux-amd64/helm

      - name: Create Helm Releases
        run : |
          for f in charts/*; do
            linux-amd64/helm package $f
          done

      - name: Switch branch and publish
        run: |
          git checkout -f gh-pages # Force ensure only new chart files get copied to the gh-pages branch
          linux-amd64/helm repo index .
          if [[ -d "linux-amd" ]]; then
            rm -rf "linux-amd"
          fi
          git add index.yaml *.tgz
          git commit -m "Upgraded the Helm index"
